name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
      - feature/mona_deploy
    paths:
      - 'terraform/**'

jobs:
  terraform-plan-and-apply:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init -reconfigure  # Garante que o backend seja configurado corretamente

      - name: Force unlock if needed
        run: |
          sudo apt-get update && sudo apt-get install -y expect  # Instala o expect
          expect -c '
          spawn terraform force-unlock fb1ed8a6-7240-e2e8-1d70-d7cb587f1004
          expect "Do you really want to force-unlock?" { send "yes\r" }
          expect eof
          '

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply tfplan
