name: Upload Lambda Scripts to S3

on:
  push:
    branches:
      - main
      - feature/mona_deploy
    paths:
      - 'lambda/*.py'

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fazer upload dos scripts para o S3
        run: |
          aws s3 sync lambda/ s3://eedb-015-2025-1-projeto-integrador-grupo-c/lambda/scripts/ --delete
