name: Upload Glue Scripts to S3

on:
  push:
    branches:
      - main             # ✅ Só executa quando o push for na branch main
    paths:
      - 'glue_jobs/**/*.py'  # ✅ Só se arquivos Python dentro de glue_jobs forem alterados

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fazer upload dos scripts para o S3
        run: |
          aws s3 sync glue_jobs/ s3://eedb-015-2025-1-projeto-integrador-grupo-c/glue/scripts/ --delete
